services:
  mongo:
    image: mongo:latest
    volumes:
      - data:/data/db
  back:
    build:
      context: .
      dockerfile: ./dockerfiles/back.Dockerfile
  front:
    build:
      context: .
      dockerfile: ./dockerfiles/front.Dockerfile
      
  # util service
  python-poetry:
    build:
      context: .
      dockerfile: ./dockerfiles/python-poetry.Dockerfile
    volumes:
      - ./apps/back:/app

  react:
    build:
      context: .
      dockerfile: ./dockerfiles/react.Dockerfile
    volumes:
      - ./apps/front:/app/my-app

volumes:
  data:
