services:
  mongo:
    image: mongo:latest
    volumes:
      - data:/data/db
  back:
    build:
      context: .
      dockerfile: ./dockerfiles/back.Dockerfile
    depends_on:
      - mongo
    ports:
      - "8000:8000"
  front:
    build:
      context: .
      dockerfile: ./dockerfiles/front.Dockerfile
    depends_on:
      - back
    ports:
      - "8080:8080"
      
  # util service
  python-poetry:
    build:
      context: .
      dockerfile: ./dockerfiles/python-poetry.Dockerfile
    volumes:
      - ./apps/back:/app

  react:
    build:
      context: .
      dockerfile: ./dockerfiles/react.Dockerfile
    volumes:
      - ./apps/front:/app/my-app

volumes:
  data:
